#!/usr/bin/env bash
# Quick Start Script - Threat-Radar Frontend-Backend Integration
# 
# This script demonstrates how everything is integrated
# Usage: Follow the steps below manually or use npm run dev:full

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║       THREAT-RADAR FRONTEND-BACKEND INTEGRATION READY         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 SYSTEM ARCHITECTURE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ┌─────────────────────────────────────────────┐"
echo "  │    FRONTEND (Vite - React)                  │"
echo "  │    URL: http://localhost:5173               │"
echo "  │    Component: CyberHealthAnalyzer           │"
echo "  │                                             │"
echo "  │    ┌───────────────────────────────────┐   │"
echo "  │    │ Enter System Symptoms             │   │"
echo "  │    │ \"slow performance high cpu\"       │   │"
echo "  │    │ [Run Threat Scan Button]          │   │"
echo "  │    └───────────┬───────────────────────┘   │"
echo "  │                │ fetch('/api/threat-radar')│"
echo "  └────────────────┼─────────────────────────────┘"
echo "                   │"
echo "          [VITE PROXY ROUTER]"
echo "          localhost:5173 → localhost:3001"
echo "                   │"
echo "  ┌────────────────▼─────────────────────────────┐"
echo "  │    BACKEND (Express Node.js)                │"
echo "  │    URL: http://localhost:3001               │"
echo "  │    Server: dev-server.js                    │"
echo "  │                                             │"
echo "  │    ┌───────────────────────────────────┐   │"
echo "  │    │ POST /api/threat-radar             │   │"
echo "  │    │ 1. Extract symptoms                │   │"
echo "  │    │ 2. Calculate probabilities         │   │"
echo "  │    │ 3. Rank threats                    │   │"
echo "  │    │ 4. Generate mitigation steps       │   │"
echo "  │    └───────────┬───────────────────────┘   │"
echo "  │                │                            │"
echo "  │    ┌───────────▼───────────────────────┐   │"
echo "  │    │ threatAnalysisEngine.js            │   │"
echo "  │    │ Local threat analysis logic        │   │"
echo "  │    └────────────────────────────────────┘   │"
echo "  └────────────────────────────────────────────────┘"
echo "                   │"
echo "        [Return JSON Response]"
echo "   Risk Level, Score, Threats, Mitigation"
echo "                   │"
echo "  ┌────────────────▼─────────────────────────────┐"
echo "  │    FRONTEND DISPLAYS RESULTS               │"
echo "  │    • Risk gauge (0-100%)                    │"
echo "  │    • Threat cards                           │"
echo "  │    • Action steps                           │"
echo "  └─────────────────────────────────────────────┘"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 QUICK START (Choose One):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Option 1: Run Everything (RECOMMENDED)"
echo "  ─────────────────────────────────────"
echo "  $ npm run dev:full"
echo ""
echo "  This starts:"
echo "  • Frontend on port 5173"
echo "  • Backend on port 3001"
echo "  • Auto-proxy configuration"
echo ""
echo "  Option 2: Run Separately"
echo "  ────────────────────────"
echo "  Terminal 1 (Backend):"
echo "  $ npm run dev:backend"
echo ""
echo "  Terminal 2 (Frontend):"
echo "  $ npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📂 FILE STRUCTURE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  cybersec-arena/"
echo "  ├── 📦 Frontend"
echo "  │   ├── src/pages/CyberHealthAnalyzer.tsx ← Main UI"
echo "  │   ├── vite.config.ts ← Proxy config"
echo "  │   └── package.json"
echo "  │"
echo "  ├── 📦 Backend"
echo "  │   ├── dev-server.js ← Dev server"
echo "  │   ├── server/index.js ← Prod server"
echo "  │   └── server/threatAnalysisEngine.js ← Logic"
echo "  │"
echo "  └── 📄 Documentation"
echo "      ├── THREAT_RADAR_SETUP.md"
echo "      ├── THREAT_RADAR_INTEGRATION.md"
echo "      ├── THREAT_RADAR_API.md"
echo "      └── THREAT_RADAR_READY.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ WHAT'S INCLUDED:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✓ Frontend Component (React + Vite)"
echo "  ✓ Backend Server (Express Node.js)"
echo "  ✓ API Endpoints (/api/threat-radar)"
echo "  ✓ Threat Analysis Engine"
echo "  ✓ Error Handling"
echo "  ✓ Automatic Proxy Routing"
echo "  ✓ CORS Configuration"
echo "  ✓ Documentation"
echo "  ✓ Test Scripts"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 HOW TO USE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Start servers:"
echo "     $ npm run dev:full"
echo ""
echo "  2. Open browser:"
echo "     http://localhost:5173"
echo ""
echo "  3. Navigate to ThreatRadar (Radar icon in menu)"
echo ""
echo "  4. Enter symptoms (examples):"
echo "     • \"slow performance\""
echo "     • \"high cpu usage\""
echo "     • \"unexpected pop-ups\""
echo "     • \"webcam turning on\""
echo "     • \"files encrypted\""
echo ""
echo "  5. Click \"Run Threat Scan\""
echo ""
echo "  6. View analysis results:"
echo "     • Risk level indicator"
echo "     • Risk percentage (0-100%)"
echo "     • Top threats with probabilities"
echo "     • Recommended actions"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧪 TESTING:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Run automated tests:"
echo "  $ node test-threat-radar.js"
echo ""
echo "  Test specific endpoint:"
echo "  $ npm run dev:backend"
echo "  $ curl -X POST http://localhost:3001/api/threat-radar \\"
echo "      -H \"Content-Type: application/json\" \\"
echo "      -d '{\"symptoms\":\"slow performance\"}'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 API RESPONSE EXAMPLE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  {
echo "    \"detected_symptoms\": [\"slow\", \"performance\", \"cpu\"],
echo "    \"threats\": [
echo "      {
echo "        \"threat\": \"Cryptominer\",
echo "        \"probability\": 85,
echo "        \"severity\": \"medium\",
echo "        \"description\": \"Uses CPU to mine cryptocurrency...\""
echo "      }"
echo "    ],
echo "    \"overall_risk_level\": \"medium\",
echo "    \"risk_percentage\": 65,
echo "    \"explanation\": \"MEDIUM RISK: 1 potential threat...\",
echo "    \"mitigation_strategies\": [
echo "      {
echo "        \"step\": 1,
echo "        \"action\": \"Identify Mining Process\",
echo "        \"priority\": \"high\",
echo "        \"details\": \"Find and kill suspicious process...\""
echo "      }"
echo "    ]
echo "  }"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 TROUBLESHOOTING:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Backend won't start?"
echo "  → Kill node: taskkill /F /IM node.exe"
echo ""
echo "  Port 3001 already in use?"
echo "  → netstat -ano | findstr :3001"
echo "  → taskkill /PID <PID> /F"
echo ""
echo "  Frontend can't reach backend?"
echo "  → Check backend is running on port 3001"
echo "  → Check Vite is running on port 5173"
echo "  → Open browser console (F12) for errors"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎓 DOCUMENTATION:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  📖 THREAT_RADAR_SETUP.md"
echo "     Complete setup and usage guide"
echo ""
echo "  📖 THREAT_RADAR_INTEGRATION.md"
echo "     Architecture and integration details"
echo ""
echo "  📖 THREAT_RADAR_API.md"
echo "     API documentation and examples"
echo ""
echo "  📖 THREAT_RADAR_READY.md"
echo "     Integration completion summary"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ YOU'RE ALL SET! Run this to get started:"
echo ""
echo "   npm run dev:full"
echo ""
echo "Then open: http://localhost:5173"
echo ""
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
